volumes:
  n8n_storage:
  postgres_storage:

services:
  # Phase 1: Minimal n8n + PostgreSQL only
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      # n8n Configuration
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=Asia/Jakarta
      
      # Database (using your Neon database)
      - DATABASE_URL=postgresql://neondb_owner:npg_2aPDc0HmXxGe@ep-calm-sunset-a14wr2nq-pooler.ap-southeast-1.aws.neon.tech/oipp?sslmode=require&channel_binding=require
      
      # n8n Security Keys (generated)
      - N8N_ENCRYPTION_KEY=nT2lTlJONfPc0B8PFb6h3Xv40PqmLNEV9RG372qoq7I=
      - N8N_USER_MANAGEMENT_JWT_SECRET=0NZJCNXiM2EvWpkYgBgFvda+/UPcZxHGn2GsQsq0Kp4=
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=neondb_owner
      - POSTGRES_PASSWORD=npg_2aPDc0HmXxGe
      - POSTGRES_DB=oipp
    volumes:
      - postgres_storage:/var/lib/postgresql/data
